name: Assignment4

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  GRADLE_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g
  
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
  
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Set up JDK 23.0.1
      uses: actions/setup-java@v4
      with:
          java-version: 23.0.1
          distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
          gradle-home-cache-cleanup: true

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: xvfb-run --auto-servernum ./gradlew check -x checkstyleJmh -x checkstyleMain -x checkstyleTest -x modernizer
      env:
          CI: "true"
          
    - name: Prepare format failed test results
      if: failure()
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xml-twig-tools xsltproc
        version: 1.0
        
    - name: Format failed test results
      if: failure()
      run: scripts/after-failure.sh


